<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="Ticket.aspx.cs" Inherits="CinemaApplication1.WebForm14" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style>
        .gvTicket {
            width: 100%;
            border: solid 2px black;
            margin-left: auto;
            margin-right: auto;
            border-radius: 0px 0px 15px 15px;
        }

            .gvTicket a /** FOR THE PAGING ICONS **/ {
                padding: 5px 5px 5px 5px;
                text-decoration: none;
            }

                .gvTicket a:hover /** FOR THE PAGING ICONS HOVER STYLES**/ {
                    background: cornflowerblue;
                    color: blue;
                }

            .gvTicket span /** FOR THE PAGING ICONS CURRENT PAGE INDICATOR **/ {
                background-color: #fff;
                color: #000;
                padding: 5px 5px 5px 5px;
            }

            .gvTicket td {
                padding: 5px;
                border: solid 2px black;
            }

            .gvTicket th {
                padding: 5px;
                border: solid 2px black;
            }

        body {
            background-image: url(../image/cinemaBk4.jpg);
            background-size: cover;
            background-repeat: no-repeat;
            background-attachment: fixed;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="main" runat="server">
    <br />
    <br />
    <div class="container">
        <div class="panel panel-info">
            <div class="panel-body">
                <asp:Button ID="btnBack" CssClass="btn-dark text-light btn-outline-warning px-5 py-1" runat="server" Text="Back" OnClick="btnBack_Click" />&nbsp;&nbsp;
                <asp:Button ID="btnAddTicket" CssClass="btn-dark text-light btn-outline-warning px-5 py-1" runat="server" Text="Add Ticket" OnClick="btnAddTicket_Click" /><br /><br />
                <asp:GridView ID="gvTicket" CssClass="gvTicket bg-dark text-light" BorderColor="Black" runat="server" DataSourceID="SqlDataSource2" AutoGenerateColumns="False" DataKeyNames="TicketId" AutoGenerateDeleteButton="True">
                    <Columns>
                        <asp:BoundField DataField="TicketId" HeaderText="TicketId" ReadOnly="True" SortExpression="TicketId" />
                        <asp:BoundField DataField="seat" HeaderText="seat" SortExpression="seat" />
                        <asp:BoundField DataField="hall" HeaderText="hall" SortExpression="hall" />
                        <asp:BoundField DataField="time" HeaderText="time" SortExpression="time" />
                        <asp:BoundField DataField="movieId" HeaderText="movieId" SortExpression="movieId" />
                        <asp:BoundField DataField="date" HeaderText="date" SortExpression="date" />
                        <asp:BoundField DataField="available" HeaderText="available" SortExpression="available" />
                        <asp:BoundField DataField="price" HeaderText="price" SortExpression="price" />
                    </Columns>
                </asp:GridView>
                <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT * FROM [Ticket]" DeleteCommand="DELETE from [Ticket] Where [TicketId]=@TicketId"></asp:SqlDataSource>
            </div>
        </div>
    </div>
    <br />
    <br />
    <br />
    <br />
</asp:Content>
